### PR TITLE
Fixed Character/Partner creation

### LINKED ISSUE #196: Error in Partner Creation
One of my players tried creating the new partner that just came out, I am guessing there was a change in the packaets, idk if there is something new before `partner.Lower` but that is specifically the value that it crashes at!

```
1/6/2016 10:06:47 PM [Info] - User 'yumiser' logged in.
1/6/2016 10:10:33 PM [Info] - New character 'God' created in account 'yumiser'.
1/6/2016 10:11:10 PM [Error] - There has been a problem while handling '0045', 'CreatePartner'.
1/6/2016 10:11:10 PM [Exception] - System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Aura.Login.Database.Item.CardItemsToItems(IEnumerable`1 cardItems) in c:\Users\Administrator\Documents\Aura\aura\src\LoginServer\Database\Item.cs:line 62
   at Aura.Login.Database.Account.CreatePartner(Character partner) in c:\Users\Administrator\Documents\Aura\aura\src\LoginServer\Database\Account.cs:line 142
   at Aura.Login.Network.Handlers.LoginServerHandlers.CreatePartner(LoginClient client, Packet packet) in c:\Users\Administrator\Documents\Aura\aura\src\LoginServer\Network\Handlers\Creation.cs:line 408
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in c:\Users\Administrator\Documents\Aura\aura\src\Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in c:\Users\Administrator\Documents\Aura\aura\src\Shared\Network\DefaultServer.cs:line 61
```

### PR DESCRIPTION
**Pull request by QewQew**
Adds check for missing item sets when creating characters/partners.

Fixes #196.

### CODE REVIEW

File: src/LoginServer/Network/Handlers/Creation.cs [hunk 1]
```diff
@@ -1,461 +1,225 @@
-﻿// Copyright (c) Aura development team - Licensed under GNU GPL
```
Comment (exectails) [inline src/LoginServer/Network/Handlers/Creation.cs]: What happened here? You overwrote the handlers with the Account class?

Comment (QewQew) [inline src/LoginServer/Network/Handlers/Creation.cs]: Woah. No idea what happened there. That did not show up when I previewed the changes. I used the GitHub editor for all of this.

File: src/LoginServer/Database/Account.cs [hunk 2]
```diff
@@ -137,9 +138,16 @@ public bool CreatePartner(Character partner)
 				setId = 1001;
 			else if (partner.Race == 730206)
 				setId = 1002;
+			else if (partner.Race == 730207)
```
Comment (exectails) [inline src/LoginServer/Database/Account.cs]: Maybe we should put those into the race db or something =| I assume we didn't have JSON yet when I wrote this code...
